### ISSUE TITLE
Problème dans l'import de masse 

### ISSUE THREAD

**Issue by YousraSen** [collec-science/collec-science#587]
Bonjour, 

Je suis entrain de tester des fonctions dans la fonctionnalité "import de masse", le problème c'est que lorsque j'insère le fichier CSV et que je le vérifie, ça m'affiche : La colonne 0 n'est pas reconnue (...). 
Cependant, quand j'insère le même fichier dans l'ordinateur de Monsieur Gassier, il l'accepte sans aucun soucis. 
Je vous rappelle que je travaille sur le navigateur Google Chrome. Pouvez-vous me donner une piste de où est ce que ça peut venir ou au moins me guider vers une solution ?

Je vous remercie par avance. 
Cordialement,

**Comment by equinton** [comment]
Bonjour,
c'est probablement le séparateur de colonne qui n'est pas correctement positionné. Il faut également vérifier l'encodage du fichier (utf-8)
À vérifier également la structure du fichier (guillemets, etc.).
Au besoin, envoie-moi par mail ton fichier, que je regarde directement.
Cordialement,
Éric.
