### ISSUE TITLE
Problème fichiers CSV 

### ISSUE THREAD

**Issue by YousraSen** [collec-science/collec-science#588]
Bonjour, 

J'ai détecté un problème bizarre dans l'insertion des fichiers CSV pour l'import de masse, et je n'arrive pas à savoir d'où ça vient, j'ai essayé de le débugger en passant par plusieurs alternatives, mais je ne trouve pas une solution définitive.
D'abord, j'ai un premier fichier Excel qui contient 59 colonnes. En le convertissant en CSV, je n'arrive pas à le vérifier lors de l'import de masse (problème : trois colonnes non reconnues). J'ai donc supprimé les trois colonnes, et ça a marché, pourtant elles étaient bien définies dans la collection correspondante et il n y'avait aucune erreur d'écriture ou de syntaxe. 
Ensuite, pour le deuxième fichier Excel, il contient 61 colonnes. En le convertissant en CSV, il y'a eu le même problème, donc j'ai dû supprimer la colonne et c'est passé par la suite. Pourtant, la colonne supprimée figurait bien dans les métadonnées de la collection, et encore une fois, il n y avait pas d'erreur d'écriture ou de syntaxe. 

Je me demande s'il n y a pas une condition sur le nombre de colonnes ou de caractères que doit contenir un fichier CSV parce que les colonnes que j'ai dû supprimer étaient déclarées dans les collections correspondantes et ne semblaient avoir aucun problème que ça soit dans l'écriture (espace, accent ...) ou autre.

Pouvez-vous me dire ce que vous en pensez et si vous avez une solution ou une idée en tête ? 

Je vous remercie d'avance. 

Bien cordialement, 
Yousra SENHAJI

**Comment by equinton** [comment]
Il faudrait tester en décalant les colonnes incriminées, en les plaçant plutôt dans les premières du fichier, pour vérifier si le problème ne serait pas lié à un nombre de colonnes trop important. J'avais déjà rencontré un souci il y a une bonne dizaine d'années, où un nombre de colonnes trop important me plantait mon importation ; mais c'était dans des versions PHP bien plus anciennes.
Il faudrait également vérifier les noms des colonnes, qui doivent être soit préfixées avec md_, soit correspondre à  ce qui est précisé dans le formulaire d'importation.
