### ISSUE TITLE
intégration d'échantillon via API

### ISSUE THREAD

**Issue by nherrard** [collec-science/collec-science#590]
Avec l'API apiv1sampleWrite, il n'y a pas la possibilité de mettre l'échantillon dans un conteneur ?!
Peut-être est-ce possible à partir d'un dataset mais je ne vois pas comment faire.
Nadine

**Comment by equinton** [comment]
Bonjour Nadine,
Pour le moment, non... Il faudra attendre la prochaine version, je le prévois.
On a plusieurs possibilités, mais je risque de m'orienter vers la création du mouvement par une API dédiée, à réfléchir.
Éric.

**Comment by nherrard** [comment]
Du coup avec cette manière de faire, un nouvel echantillon n'est affecté à aucun contenant ?
