### ISSUE TITLE
Erreur d'exécution dans l'API

### ISSUE THREAD

**Issue by nherrard** [collec-science/collec-science#591]
Je viens de tester l'API apiv1sampleWrite en ligne et j'ai un message d'erreur qui me dit que je n'ai pas donné de type d'échantillon alors que je l'ai fait (sampling_type_name=Ecaille)

https://colisa.collec-science.inrae.fr/index.php?module=apiv1sampleWrite&login=db_u3e_web&token=xxxx&identifier=essai_nadine&sampling_type_name=Ecaille&collection_name=Oir&sampling_date=2022-06-30&md_taxon=SAT&md_longueur=120&md_riviere=Oir&referent_name=Starck&referent_firstname=Agnès&country_code=FR&country_origin_code=FR

voici l'erreur retournée
{"error_code":400,"error_message":null,"error_detail":"Le type d'\u00e9chantillon n'a pas \u00e9t\u00e9 fourni"}

**Comment by equinton** [comment]
C'est un bug dans la doc : remplace "sampling_type_name" par "sample_type_name".
Je corrige pour la prochaine version (la doc).
