### ISSUE TITLE
problème avec l'API apiv1sampleWrite

### ISSUE THREAD

**Issue by nherrard** [collec-science/collec-science#599]
Bonjour Eric
j'ai toujours le même problème avec l'API apiv1sampleWrite à savoir qu'il ne reconnait pas le type d'échantillon.
Dans les paramètres de l'API, j'ai essayé  "sampling_type_name" et  "sample_type_name", ça ne fonctionne toujours pas
Je travaille sous R

Voici le résultat de l'execution

> requete [1] "https://colisa.collec-science.inrae.fr/index.php?module=apiv1sampleWrite&login=db_u3e_web&token=73020ba6dd03d5c4ca31ea867df1fd25d0a4c9e694d5f3fc736a8a6fc971cf0d&identifier=essai_nadine&sample_type_name=Ecaille&collection_name=Oir&sampling_date=2022-06-30&md_taxon=SAT&md_longueur=120&md_riviere=Oir&referent_name=Starck&referent_firstname=Agnès&country_code=FR&country_origin_code=FR" 

> url_collec_science_ecriture<-requete 

> r <-POST(url_collec_science_ecriture) 
> http_status(r) $category [1] "Success"  $reason [1] "OK"  $message [1] "Success: (200) OK"  

> content(r, "text") [1] "{\"error_code\":400,\"error_message\":null,\"error_detail\":\"Le type d'\\u00e9chantillon n'a pas \\u00e9t\\u00e9 fourni\"}"
--
 
> | >
>

**Comment by equinton** [comment]
Je pense que c'est lié à l'utilisation de POST, qui doit être mal utilisé. 

Voici ce que j'ai avec Jupyter : 
# Test Colisa
import requests
response = requests.post(f"{base_url}/index.php", {
    "login": login,
    "token": token,
    "module": "apiv1sampleWrite",
    "collection_name": "Oir",
    "identifier": 'essai_nadine',
    "sample_type_name": "Ecaille",
    "sampling_date": "2022-06-30",
    "md_taxon": "SAT",
    "md_longueur": 120,
    "md_riviere": "Oir",
    "referent_name": "Starck",
    "referent_firstname": "Agnès",
    "country_code": "FR",
    "country_origin_code": "FR"
})

response.json()

{'error_code': 403,
 'error_message': None,
 'error_detail': "La collection n'est pas paramétrée pour accepter les flux entrants"}

Et une fois activé le flux entrant pour la collection Oir : 
{'error_code': 200, 'uid': 158249, 'error_message': 'processed'}

Dans ton cas de figure, il faut passer les variables dans le corps du message (body), et non pas dans l'adresse (c'est alors du GET). Tu peux regarder l'exemple donné ici : https://www.rdocumentation.org/packages/httr/versions/1.4.3/topics/POST

D'autre part, je viens de régénérer le token : le fait de l'avoir posté dans github fait sauter la sécurité.
