### ISSUE TITLE
connexion API

### ISSUE THREAD

**Issue by yannickkk** [collec-science/collec-science#605]
Bonjour Eric,

J'essaye de me connecter via R et l'API sur mon notre instance de collec science mais visiblement je n'y parviens pas. 
Pour se faire, j'ai créé un rôle avec login et un token.
La ligne ci-dessous me renvoi un status 200 mais renvoi du HTML, visiblement pas ce que j'attends puisque je devrais avoir du json en retour.
GET(paste0(url = "cefs.collec-science.inrae.fr/index.php?module=sampleDetail&uid=",uid,"&login=",login,"&token=",token,""))

Si tu vois de quoi il s'agit ??
merci
Yannick

**Comment by equinton** [comment]
C'est une limitation de l'identification en mode Shibboleth (passage par l'infra Renater) : les services web sont inopérants dans ce cas de figure.
Dans la pratique, le serveur web ne donne l'accès à l'application qu'après identification via Renater, c'est à dire que ça impose le dialogue via l'interface Renater. L'accès par API est dès lors impossible.
La seule solution, c'est de créer une nouvelle entrée DNS qui pointera vers la même base de données, mais qui utilisera une identification différente, par exemple api-cefs.collec-science.inrae.fr. On pourra alors lancer les requêtes d'API via cette adresse dédiée.
Il faudrait demander à Florent de créer cette entrée DNS, avec une identification en base de données. Je lui envoie un message en ce sens.
Éric.

**Comment by equinton** [comment]
Entrée DNS créée, possibilité de créer un compte API.
