### ISSUE TITLE
problème d'affectation d'un echantillon dérivé à une collection

### ISSUE THREAD

**Issue by nherrard** [collec-science/collec-science#607]
Bonjour Eric,
On rencontre un soucis avec Agnès pour la création des échantillons dérivés. On part d'un échantillon d'une collection donnée (CNICS par exemple) et on créé un échantillon dérivé. Dans le champ collection on est embêtées car a priori cela devrait être la même collection que le parent mais dans la liste déroulante, moi je n'ai que la collection OIR qui m'est proposée et Agnès a les collection OIR et SCORFF. Comment sont gérées ces listes, ce n'est pas une question de droits car on arrive à créer des échantillons dans toutes nos collections.
Merci pour ton aide
Nadine et Agnès

**Comment by nherrard** [comment]
ok mais si on prend l'exemple d'Agnès, elle est dans le groupe de login "gestion_cnics"
Dans paramètre/collections, la collection CNIS donne les droits à param_cnics et gestion_cnics, 
ça n'empêche qu'elle ne peut pas créer d'échantillons dérives dans la collection CNICS
il y a quelque chose qu m'échappe ..

**Comment by equinton** [comment]
See issue #611
