### ISSUE TITLE
Pb de recherche au niveau de l'onglet "Localisation "

### ISSUE THREAD

**Issue by spetek29** [collec-science/collec-science#608]
Bonjour,

Merci pour cette nouvelle version!!

Je viens de tester l'onglet localisation pour rechercher de échantillons (sans utilisation des autres onglets):

Si on utilise "Lieu de prélèvement": on obtient bien la liste des échantillons pour un endroit donné, par contre ils ne s'affichent pas sur la carte (c'est peut-être normal?)

Si on utilise "Pays de collecte" uniquement: en mettant "France" par exemple, il n'y a aucun résultat qui sort.

De la même manière, si on utilise "Pays de provenance" uniquement: en mettant "France" par exemple, il n'y a aucun résultat qui sort.

Quelle différence faites-vous entre "Pays de collecte" et "Pays de provenance"? C'est pour le cas où un chercheur français par exemple va collecter dans un autre pays et qu'il ramène les échantillons en France?

Bonne journée,

Sylvain

**Comment by equinton** [comment]
Pour que les échantillons s'affichent sur la carte, il faut que les coordonnées XY aient été renseignées. L'appli est capable de "forcer" ces coordonnées depuis la station, si celle-ci a elle-même une coordonnée renseignée, au moment de la modification.
Pour le pays de collecte ou le pays de provenance, là encore, il faut que les informations soient renseignées pour que la recherche fonctionne.
Ces deux informations sont liées à la réglementation APA. Le pays de collecte est le pays où l'échantillon a été physiquement récupéré. Le pays de provenance est le pays qui a fourni l'échantillon.
Ainsi, un échantillon peut être collecté au Gabon par une équipe espagnole, qui va le transmettre ensuite à un labo français : le pays de collecte sera le Gabon, le pays de provenance, l'Espagne.
