### ISSUE TITLE
Bug version 2.8.0

### ISSUE THREAD

**Issue by yannickkk** [collec-science/collec-science#614]
Bonjour Eric,

j'ai, je pense, un soucis avec la Version 2.8.0. Je dis je pense car depuis la montée de version j'ai fait un import de masse donc je ne peux pas exclure que le problème vienne de là mais je doute. 
Lorsque je suis sur la page d'accueil Collec m’affiche 9115 échantillons pour la collection VCG

![image](https://user-images.githubusercontent.com/39738426/194868338-7a3717c2-8937-4420-bcef-775bb2c206e5.png)

Et lorsque je sélectionne les échantillons de VCG il m’en sort 20 sur 6977 ?
 
![image](https://user-images.githubusercontent.com/39738426/194868404-6a1d42b2-2500-4625-8672-bf2a266f304d.png)

Yannick

**Comment by yannickkk** [comment]
bug version 2.8.0

**Comment by equinton** [comment]
tu peux m'indiquer le nom de ton instance, que j'aille regarder ? Au besoin, envoie-moi un mail

**Comment by equinton** [comment]
Problème réglé en vidant le cache du navigateur
