### ISSUE TITLE
Génération de fichiers au format ELN

### ISSUE THREAD

**Issue by equinton** [collec-science/collec-science#619]
Ajouter la génération de fichiers contenant des échantillons au format ELN, pour pouvoir être intégrés dans des logiciels de labo électronique

**Comment by NicolasCARPi** [comment]
And here is the link to the repository with the specification and examples: https://github.com/TheELNConsortium/TheELNFileFormat

**Comment by equinton** [comment]
Le format ELN n'est pas adapté aux échanges entre Elabftw et collec-science (trop complexe, nécessiterait un programme dédié, inenvisageable dans le contexte collec-science). Tests à réaliser en csv pour alimenter (ou récupérer) depuis une catégorie d'objets.

**Comment by equinton** [comment]
Le format d'exportation CSV de ElabFTW ne permet pas des importations dans Collec-Science (regroupement de toutes les informations dans un champ json).
Il est par contre possible d'alimenter Elab à partir de Collec-Science, sachant que les données fournies seront stockées dans un seul champ (texte principal).
