### ISSUE TITLE
mouvement petit terminal version 2.8.0

### ISSUE THREAD

**Issue by yannickkk** [collec-science/collec-science#634]
Bonjour Eric,

Lorsque nous essayons d'affecter une boite d'échantillons (qui est connue de collec) à un congélateur (connu également) ou lorsque nous désirons bouger une boite d'une congélateur vers un autre (là aussi collec connait tout le monde), l'application affiche le message d'erreur:
"impossible d'enregistrer le mouvement"
Dans la version précédente, ses mouvements ne posaient pas de problèmes.
Peux tu regarder s'il te plait.
merci
Yannick

**Comment by equinton** [comment]
Ok, je confirme le bug.
En attendant la prochaine version (dès que je peux), tu peux utiliser la création des mouvements depuis la liste des échantillons : ça fonctionne.

**Comment by yannickkk** [comment]
Exact on vient d’essayer depuis la liste des contenants (car elle veut bouger des boites) effectivement ça fonctionne.

Merci bonne soirée

yannick

 

De : Eric Quinton ***@***.***> 
Envoyé : lundi 7 novembre 2022 17:35
À : collec-science/collec-science ***@***.***>
Cc : yannickkk ***@***.***>; Author ***@***.***>
Objet : Re: [collec-science/collec-science] mouvement petit terminal version 2.8.0 (Issue #634)

 

Ok, je confirme le bug.
En attendant la prochaine version (dès que je peux), tu peux utiliser la création des mouvements depuis la liste des échantillons : ça fonctionne.

**Comment by equinton** [comment]
Corrigé, il y avait un bug (au moins)

**Comment by equinton** [comment]
Tu peux réessayer ? J'ai corrigé un des bugs, ça devrait suffire pour que ça fonctionne (j'espère)

**Comment by yannickkk** [comment]
Salut Éric, je n'étais pas au labo aujourd'hui et en réunion sans internet d'où ma réponse tardive, j'essaye demain matin et je te tiens au courant, bonne soirée.
Yannick

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yannickkk** [comment]
Bonjour Eric,

Jai testé ça marche, merci

Bonne journée

yannick

 

De : Yannick Chaval ***@***.***> 
Envoyé : mardi 8 novembre 2022 18:06
À : collec-science/collec-science
***@***.***>;
collec-science/collec-science ***@***.***>
Cc : Yannick Chaval ***@***.***>; Author
***@***.***>
Objet : Re: [collec-science/collec-science] mouvement petit terminal version
2.8.0 (Issue #634)

 

Salut Éric, je n'étais pas au labo aujourd'hui et en réunion sans internet
d'où ma réponse tardive, j'essaye demain matin et je te tiens au courant,
bonne soirée.

Yannick

 

Obtenir Outlook pour Android <https://aka.ms/AAb9ysg> 

  _____
