### ISSUE TITLE
Sélection de plusieurs échantillons dont les UID ne se suivent pas

### ISSUE THREAD

**Issue by astarck35310** [collec-science/collec-science#658]
Bonjour,
pour sélectionner plusieurs, nombreux, échantillons dont les UID ne se suivent pas ( afin par exemple de leur attribuer le même évènement) il faut que je le fasse en les cherchant 1 par 1 ce qui prend du temps ! serait possible de pouvoir les sélectionner en renseignant une "fourchette" comme pour les UID ou en les notant à la suite dans le pavé "identifiant"?
Merci !
Cordialement
Agnès

**Comment by equinton** [comment]
Ajout de la recherche multiple dans la zone identifiant(s), séparateur : virgule
