### ISSUE TITLE
problème de recherche avec la nouvelle version 2.8.2 

### ISSUE THREAD

**Issue by nherrard** [collec-science/collec-science#659]
Bonjour Eric,
Nous rencontrons des problèmes de recherche avec la nouvelle version.
- Recherche uniquement sur la collection : Agnès n'arrive plus à voir les échantillon des collections Oir et scorff, mais elle voit ceux de la collection marins_amphihalins. Moi je vois tous les échantillons de toutes les collections.
- Recherche d'un échantillon donné : les recherches par identifiant n'aboutissent pas (échantillon CBA_00118-01 de la collection marins_amphihalins par exemple)
- Recherche par uid fonctionne mais il faudrait que le champ soit un peu plus large
Merci d'avance
Nadine

**Comment by equinton** [comment]
Correction de la recherche par identifiant réalisée.
