### ISSUE TITLE
La recherche à partir d'un évènement n'aboutit pas

### ISSUE THREAD

**Issue by nherrard** [collec-science/collec-science#660]
Bonjour Eric,
Nous n'arrivons plus à effectuer une recherche par type d'évènement, on arrive sur une page vierge et on perd la main.
Exemple sur l'instance U3E, recherche sur FishLegs.
Agnès et Nadine

**Comment by equinton** [comment]
Corrigé, ainsi que d'autres problèmes détectés dans les traces, tous liés à la nouvelle version de PHP.
