### ISSUE TITLE
trie

### ISSUE THREAD

**Issue by yannickkk** [collec-science/collec-science#661]
Bonjour Eric,

Dans les version précédentes on pouvait chercher directement dans le data table. Dans la nouvelle version on ne peut plus le faire. On est obligé de jongler dans les divers onglets de recherche et en général ça fini par planter.
Pourquoi avoir supprimer cette fonctionnalité ?

**Comment by equinton** [comment]
Bonjour Yannick,
Tu peux toujours rechercher dans le tableau, tu disposes d'une zone en haut à droite de celui-ci : 

![Capture d’écran du 2023-03-07 09-17-01](https://user-images.githubusercontent.com/6715861/223364688-5914ce63-d94a-45f8-ad6a-f32b212d35e4.png)

Je ne pouvais pas maintenir l'ancien fonctionnement et conserver les entêtes des colonnes toujours visibles quand on scrolle dans le tableau. 

Après, on peut toujours mettre une option pour conserver la recherche par colonne comme elle existait auparavant, j'y réfléchirai pour la prochaine version.

**Comment by yannickkk** [comment]
Bonsoir Eric,

 

Oui il y a une barre de recherche mais quand il y avait une barre de recherche dans chaque champ, on pouvait faire des recherches emboitées très facilement. Je trouve ça moins pratique maintenant personnellement.

Donc à l’occas d’une autre version je suis preneur de filtre par colonne.

 

Bonne soirée

Yannick

 

 

De : Eric Quinton ***@***.***> 
Envoyé : mardi 7 mars 2023 09:24
À : collec-science/collec-science ***@***.***>
Cc : yannickkk ***@***.***>; Author ***@***.***>
Objet : Re: [collec-science/collec-science] trie (Issue #661)

 

Bonjour Yannick,
Tu peux toujours rechercher dans le tableau, tu disposes d'une zone en haut à droite de celui-ci :

 <https://user-images.githubusercontent.com/6715861/223364688-5914ce63-d94a-45f8-ad6a-f32b212d35e4.png> 

Je ne pouvais pas maintenir l'ancien fonctionnement et conserver les entêtes des colonnes toujours visibles quand on scrolle dans le tableau.

Après, on peut toujours mettre une option pour conserver la recherche par colonne comme elle existait auparavant, j'y réfléchirai pour la prochaine version.
