### ISSUE TITLE
Problème à l'import de masse pour des contenants

### ISSUE THREAD

**Issue by nherrard** [collec-science/collec-science#679]
Eric,
Nous n'arrivons pas à importer un fichier de contenants. La phase de controle se passe bien et après le déclenchement on a un message qui nous dit que tout s'est bien passé mais les numéro id importé restent vides.
Ci-joint le fichier importé et le message qui s'affiche suite à l'insertion
[import_boites_génétiques.csv](https://github.com/collec-science/collec-science/files/11498732/import_boites_genetiques.csv)
![erreur_import_contenant](https://github.com/collec-science/collec-science/assets/71451173/bfcd118c-96b8-4b31-bb06-f2769fbda718)
.

Merci
Agnès et Nadine

**Comment by equinton** [comment]
Bonjour,
Le fichier est encodé en iso-8859-1 : lors de l'importation, vous devez modifier l'encodage du fichier en iso-8859-xx
Je regarderai si je peux tester l'encodage dans une prochaine version.

**Comment by nherrard** [comment]
Bonjour Eric,
Merci, c’était bien ça l’erreur mais oui, ce serait bien de détecter cette erreur et d’afficher un message à l’utilisateur.
Bonne journée
Nadine

De : Eric Quinton ***@***.***>
Envoyé : mardi 23 mai 2023 12:11
À : collec-science/collec-science ***@***.***>
Cc : Nadine Renault ***@***.***>; Author ***@***.***>
Objet : Re: [collec-science/collec-science] Problème à l'import de masse pour des contenants (Issue #679)


Bonjour,
Le fichier est encodé en iso-8859-1 : lors de l'importation, vous devez modifier l'encodage du fichier en iso-8859-xx
Je regarderai si je peux tester l'encodage dans une prochaine version.
