### ISSUE TITLE
Ajout de "sample_location" dans les étiquettes 

### ISSUE THREAD

**Issue by YousraSen** [collec-science/collec-science#683]
Bonjour Eric, 

Serait-il possible d'ajouter la donnée "sample_location" dans les étiquettes (QR-code) ? En effet, on veut afficher cette information sur les étiquettes mais on y arrive pas.  

Merci d'avance. Cordialement, 
Yousra SENHAJI

**Comment by equinton** [comment]
Bonjour Yousra,
Qu'entendez-vous par "sample_location" ? Il est actuellement possible d'indiquer la station (sampling_place_name avec la variable loc). Par contre, il n'est pas prévu d'indiquer le contenant, sachant que celui-ci n'est pas pérenne.
Si vous souhaitez indiquer une information pérenne, ce serait plus dans les métadonnées qu'il faudrait les renseigner.
À discuter, donc...
Éric.

**Comment by ghislainGASSIER** [comment]
Bonjour Eric

pour clarifier notre besoin,

nous sommes plus précisément enclins à rendre pérenne les emplacements des échantillons afin qu'ils apparaissent sur les étiquettes. La raison est essentiellement "educative" pour inciter les chercheurs à respecter les lieux de stockage et maintenir collec à jour (pour rappel nos emplacements sont libres d'accès).

les informations qui sont des données, et que nous souhaitons faire apparaitre sont:
- container_location
- container_line
- container_colonne
est il possible de les regrouper et de les rendre accessible pour impression sur les étiquettes ?

sampling place...etant deja accessibles

merci!
