### ISSUE TITLE
Génération d'étiquettes EAN128

### ISSUE THREAD

**Issue by cehuneau** [collec-science/collec-science#689]
Bonjour,
Suite à des tests de création de modèles d'étiquettes, aucun problème pour générer des QRcodes, par contre si on sélectionne le type EAN 128, on obtient une erreur serveur. J'ai laissé un exemple sur l'instance de démo.

**Comment by equinton** [comment]
Les codes-barres 1D ne peuvent pas contenir plusieurs champs différents : il faut indiquer que le code ne contient qu'un champ, et choisir le type de donnée que l'on souhaite, soit uid, soit id.
J'ai créé un exemple. Par contre, cela m'a permis de voir qu'il y avait des problèmes de fonctionnement de l'interface (pas de possibilité de dupliquer une étiquette, libellés en double, etc.)
