### ISSUE TITLE
etiquette EAN 128

### ISSUE THREAD

**Issue by Boutrot** [collec-science/collec-science#692]
Bonjour,
dans la version démo en ligne, la génération de code-barres de type EAN 128 ne semble pas fonctionner. 
Si ces codes-barres nécessitent un code XSL particulier, serait-il possible d'ajouter un exemple parmi la liste de modèles proposés?
merci d'avance.

**Comment by equinton** [comment]
Les codes-barres 1D ne peuvent pas contenir plusieurs champs différents : il faut indiquer que le code ne contient qu'un champ, et choisir le type de donnée que l'on souhaite, soit uid, soit id.
J'ai créé un exemple. Par contre, cela m'a permis de voir qu'il y avait des problèmes de fonctionnement de l'interface (pas de possibilité de dupliquer une étiquette, libellés en double, etc.)
