### ISSUE TITLE
Problème de décalage d'affichage dans les paramètres

### ISSUE THREAD

**Issue by equinton** [collec-science/collec-science#699]
Bonjour, Mathias m'indique aussi qu'il y aurait un décalage entre la liste des types dans les paramètres et dans les options des échantillons. Il s'agit de l'instance IUEM. cf. PJ

![collec_types2](https://github.com/collec-science/collec-science/assets/6715861/4fccd01c-e8c3-43d5-ada5-5460cac3a3c8)

![collec_types](https://github.com/collec-science/collec-science/assets/6715861/4ce75a2a-e8cb-42f0-8c0c-e0457358eb71)

**Comment by spetek29** [comment]
Bonjour,
C'est moi qui ai signalé ce problème à Mathias. 
En fait, c'est surtout qu'au niveau du formulaire échantillon, certains types n'apparaissent pas dans la liste, alors qu'ils figurent bien dans les paramètres.
Merci d'avance pour votre aide.
Bonne journée,
Sylvain

**Comment by equinton** [comment]
C'est quoi, l'adresse de l'instance ? Il faut que je regarde la config.

**Comment by spetek29** [comment]
https://iuem.collec-za.org/

**Comment by equinton** [comment]
Peux-tu être plus précis ? Quels types d'échantillons manquent, pour quelle collection ? 
Pour info, dans la version actuelle de l'appli, le fait de rattacher un type d'échantillon à une collection le rend "invisible" pour les autres collections : cela permet d'éviter de surcharger les listes avec des types spécifiques.

**Comment by spetek29** [comment]
Bonjour Eric,
Merci beaucoup pour cette information, je n'étais pas au courant. Je n'avais aucun type d'échantillon rattaché à mes collections.
Je viens de trouver où rattacher mes types d'échantillon à mes collections, et ça y est je les vois!!
Je me doutais qu'il y avait qqchose de ce type, mais je n'étais pas allé voir du côté des collections.
Merci beaucoup pour votre aide!
Bonne journée,
Sylvain
