### ISSUE TITLE
Pb de déplacement d'une grande quantité d'échantillons entre contenants (plus de 900 en même temps)

### ISSUE THREAD

**Issue by nherrard** [collec-science/collec-science#700]
Bonjour Eric,
On vient d'équiper notre salle de stockage avec de "belles" armoires (type pharmacie). Agnès transfère tous les échantillons par série. Elle rencontre un soucis dès qu'elle demande à transférer plus de 900 échantillons environ. On n'arrive pas à savoir ce qui pose problème, en fait l'application, soit elle ne répond pas (écran blanc) soit elle re-affiche les échantillons mais ils ne sont pas déplacés. Je suis allée voir les logs (manip d'hier), tout est à OK, je ne vois pas de problème.
Nadine

**Comment by equinton** [comment]
J'ai augmenté le nombre de variables autorisées au niveau du serveur : peux-tu refaire un test ? Si ça se reproduit, donne-moi l'heure exacte de l'opération, que je puisse regarder dans les logs du serveur.
