### ISSUE TITLE
pb checkbox

### ISSUE THREAD

**Issue by Carol-Moreau** [collec-science/collec-science#702]
Bonjour,

J'ai créé un jeu de métadonnées. 
Lorsque le type de champ est "checkbox",  il apparait ":Array" dans le tableau de données de l'échantillon au lieu de la valeur renseignée,.

merci

**Comment by equinton** [comment]
Je rencontre le souci uniquement en exportation vers une autre base de données :
![image](https://github.com/collec-science/collec-science/assets/6715861/f805bd3b-cfb8-40db-93b9-89d8d81cc1fc)
et également dans l'affichage à la volée sur la liste
