### ISSUE TITLE
Erreur 500 - Modifier le statut des échantillons cochés

### ISSUE THREAD

**Issue by ojsd** [collec-science/collec-science#704]
Bonjour,

Sur le site de démo, depuis la page des échantillons (https://demo.collec-science.inrae.fr/index.php?module=sampleList) : 
- cocher un ou plusieurs échantillons,
- dans la zone du bas "Pour les élements cochés", sélectionner "**Modifier le statut**", puis "Objet détruit" (ou autre, c'est pareil pour tous ceux que j'ai testé)
--> message de confirmation puis **erreur 500**

Bon courage !
OJ

**Comment by equinton** [comment]
Fatal error: Uncaught TypeError: Sample::setParent(): Argument #2 ($parent_id) must be of type int, null given, called in /home/equinton/web/collec/modules/gestion/sample.php on line 816 and defined in /home/equinton/web/collec/modules/classes/sample.class.php:1377 Stack trace: #0 /home/equinton/web/collec/modules/gestion/sample.php(816): Sample->setParent() #1 /home/equinton/web/collec/framework/controller.php(619): include('...') #2 /home/equinton/web/collec/index.php(3): include('...') #3 {main} thrown in /home/equinton/web/collec/modules/classes/sample.class.php on line 1377
