### ISSUE TITLE
Pb d'affichage des types d'évènements

### ISSUE THREAD

**Issue by spetek29** [collec-science/collec-science#718]
Bonjour,

Sur l'instance https://iuem.collec-za.org/, je rencontre un problème lorsque je souhaite saisir un événement pour un lot d'échantillons. 

Je n'arrive pas toujours à avoir toute la liste des types d'évènement. 

Ce qui est perturbant, c'est que la liste entière des types d'évènement s'affiche bien, si j'ai au préalable demandé l'affichage de tous les échantillons d'une collection. Par contre, si je fais une recherche pour n'afficher que les échantillons qui m'intéressent (au sein de la même collection), dans ce cas je n'ai plus qu'un seul type d'évènement voire parfois aucun qui s'affiche...

Merci d'avance pour votre aide.

Bonne journée,

Sylvain

![Types evenement liste - 2024-01-12_13h26_56](https://github.com/collec-science/collec-science/assets/85734005/c26cf8da-8626-401b-97d9-eb3c7bcfda21)
![Type evenement seul - 2024-01-12_13h25_51](https://github.com/collec-science/collec-science/assets/85734005/c2a127a0-eb85-41f0-aed3-c3770a5bf482)

**Comment by equinton** [comment]
C'est lié au fonctionnement particulier des types d'événements qui ont été rattachés à une collection.
Dès lors qu'un type d'événement est rattaché à une collection, il n'est plus visible que pour les collections qui lui ont été affectées, et à condition que la collection soit sélectionnée.
Dans ton cas de figure, seuls deux types d'événements ne sont pas affectés à des collections : je t'ai créé une requête pour que tu puisses les consulter.

Je te conseille de ne conserver le rattachement d'événements à des collections que pour les événements très "pointus" et totalement inféodés à des collections particulières.

**Comment by spetek29** [comment]
Merci Eric pour ces précisions.
Bonne journée,
Sylvain
