### ISSUE TITLE
Fusion de métadonnée

### ISSUE THREAD

**Issue by ghislainGASSIER** [collec-science/collec-science#720]
Bonjour

nous avons créer 2 métadonnée “md_resume” et “md_autre” que nous souhaitons maintenant fusionner en une seule. Pourrais tu nous donner la meilleure stratégie à adopter.

Merci,

**Comment by equinton** [comment]
Si j'analyse la demande, c'est : 

- prendre la valeur d'une des métadonnées pour la rajouter à l'autre, au besoin en insérant un séparateur
- supprimer ensuite la métadonnée en trop ?

Le plus évident est de réaliser l'opération en SQL, mais cela implique d'avoir un accès direct à la base de données, et c'est dangereux en cas d'erreur dans le script ! Tu peux t'appuyer sur la procédure de renommage d'un champ de métadonnées tel qu'elle est décrite dans le logiciel (documentation > Échantillons > Renommer un champ de métadonnées.

Ça donnerait quelque chose comme ça : 
```
update col.sample 
set metadata = jsonb_insert(metadata::jsonb, '{"resume"}'::text[],  (metadata->'resume'  || metadata->'autre)::jsonb ) - 'autre'
where metadata ->> 'autre' is not null
```
Sinon, il faut faire un export et modifier dans LibreOffice les métadonnées pour les fusionner. Néanmoins, le champ "autre" resterait présent.

**Comment by ghislainGASSIER** [comment]
oui l'analyse est bonne, j'avais identifié cette procédure de renommage. Ici ce que tu me le propose  concatène les deux colonnes de metadonnée  “resume”et “autre” et finit par supprimer “autre”?
