### ISSUE TITLE
 Beug de suppression des modéles de metadonnées

### ISSUE THREAD

**Issue by ghislainGASSIER** [collec-science/collec-science#722]
Bonjour,

Nous ne parvenons pas a supprimer un modèle de métadonnée qui est pourtant vide.

Merci le CEREGE,

**Comment by equinton** [comment]
Il est très probable que le modèle soit référencé dans la base de données, soit dans un type d'échantillons, soit dans un modèle d'étiquettes.
Pour s'en assurer : 

```
select sample_type_name 
from sample_type 
join metadata using (metadata_id)
where metadata_name = 'nom_du_modele'
```

et 

```
select label_name 
from label 
join metadata using (metadata_id)
where metadata_name = 'nom_du_modele'
```
