### ISSUE TITLE
Sous-echantillonage : erreur 500

### ISSUE THREAD

**Issue by cehuneau** [collec-science/collec-science#723]
Nous rencontrons un problème avec le sous-échantillonage.

Au niveau reproductibilité :
- On entre dans un échantillon
- Dans l'onglet "sous-echantillonage" nous faisons "Nouveau..." et rentrons une quantité en mg
- A la validation nous obtenons une erreur 500
- Par la suite, quand nous voulons retourner sur la fiche de l'échantillon, celui-ci n'est plus accessible, même erreur : 
Cette page ne fonctionne pas
Impossible de traiter cette demande via paleolab.collec-science.inrae.fr à l'heure actuelle.
HTTP ERROR 500

**Comment by equinton** [comment]
Pb d'affichage quand la quantité initiale n'a pas été renseignée

**Comment by equinton** [comment]
La correction sera dispo dans la version corrective de fin janvier.
