### ISSUE TITLE
probléme import de masse

### ISSUE THREAD

**Issue by ghislainGASSIER** [collec-science/collec-science#724]
Bonjour Eric,
J'ai une erreur lors de l'insertion e masse :+1: Une erreur s'est produite pendant l'importation.
Une erreur s'est produite pendant l'importation.

Line 2 : error when import sample - SQLSTATE[XX000]: Internal error: 7 ERROR: could not load library "/usr/lib/postgresql/11/lib/postgis-2.5.so": /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libSFCGAL.so.1) 

[test emplacement.csv](https://github.com/collec-science/collec-science/files/13987217/test.emplacement.csv)

qu'en penses tu?
Merci,
Ghislain

**Comment by equinton** [comment]
Bonjour Ghislain,
C'est probablement lié au fait que la base de données a dû être upgradée vers une version récente de Postgresql, mais postgis n'a probablement pas été remis en place. Il faut voir avec le collègue qui gère le serveur.
Éric.
