### ISSUE TITLE
Problème étiquette - mauvaise prise en compte de l'emplacement

### ISSUE THREAD

**Issue by ghislainGASSIER** [collec-science/collec-science#725]
Bonjour,Eric,
je teste les emplacements sur les étiquettes :  voici ce que j'ajoute : 

<fo:block font-size="0.53cm" margin-top="2cm">stor : <fo:inline font-weight="bold" font-size="0.80cm"><xsl:value-of select="stor"/></fo:inline></fo:block>
<fo:block font-size="0.53cm" margin-top="2cm">colonne : <fo:inline font-weight="bold" font-size="0.80cm"><xsl:value-of select="cnum"/></fo:inline></fo:block>
<fo:block font-size="0.53cm" margin-top="2cm">ligne : <fo:inline font-weight="bold" font-size="0.80cm"><xsl:value-of select="lnum"/></fo:inline></fo:block>
Mais dans le résultat le stor correspond au  nom de l'échantillon

[etiquette.pdf](https://github.com/collec-science/collec-science/files/13987445/etiquette.pdf)

on devrait avoir:  	
CS11
col:1 ligne:3 

merci,
ghislain

**Comment by equinton** [comment]
Vue mal construite, nouvelle version à prévoir.
Correction possible en attendant la nouvelle version : exécuter ce script dans la base de données
```

CREATE OR REPLACE VIEW col.last_movement
AS 
SELECT m.uid,
    m.movement_id,
    m.movement_date,
    m.movement_type_id,
    m.container_id,
    c.uid AS container_uid,
    o2.identifier AS container_identifier,
    m.line_number,
    m.column_number,
    m.movement_reason_id
   FROM col.movement m
     JOIN col.object o ON m.movement_id = o.last_movement_id
     LEFT JOIN col.container c USING (container_id)
     left join col.object o2 on (c.uid = o2.uid);
-- ddl-end --
ALTER VIEW col.last_movement OWNER TO collec;
-- ddl-end --

CREATE or replace view col.slots_used
AS 
SELECT
   container_id, count(*) as nb_slots_used
FROM
   col.last_movement
WHERE
   movement_type_id = 1
   group by container_id;
-- ddl-end --
ALTER VIEW col.slots_used OWNER TO collec;
```
