### ISSUE TITLE
Problème lecture QR avec un petit terminal

### ISSUE THREAD

**Issue by pauline-chauvet** [collec-science/collec-science#728]
Bonjour,
Nous avons fait plusieurs essais de lecture du QR code avec plusieurs téléphones/ordinateurs (multiples configurations et navigateurs web). On voit que cela déclenche la caméra des appareils mais nous n'avons pas le retour vidéo et donc pas de moyen de "valider" la lecture du QR code.
Y-a-t-il une manip particulière à faire ?
Merci,
Cordialement,
Pauline

**Comment by equinton** [comment]
Bonjour,
Le module qu'on avait mis en place au démarrage du logiciel ne fonctionne pas bien. Actuellement, seule la lecture par douchette est vraiment opérationnelle.
J'essaierai de voir si je peux remplacer le mécanisme actuellement codé par un plus moderne, pour que ça fonctionne de nouveau, soit dans la prochaine version (en cours de préparation), soit pour la suivante.

**Comment by equinton** [comment]
Mise en place d'une nouvelle bibliothèque : tests ok sur PC (en QRcode).
À voir l'efficacité et l'ergonomie avec un terminal
