### ISSUE TITLE
Possibilité de récupérer les métadonnées directement depuis le IGSN [Question]

### ISSUE THREAD

**Issue by pauline-chauvet** [collec-science/collec-science#729]
Bonjour,
Nous voulions savoir s'il était possible d'utiliser les informations de la fiche IGSN d'un échantillon pour remplir automatiquement les champs d'information lors de la création d'un nouvel échantillon dans collec-science. Cela éviterai un double travail.
J'ai vu dans la documentation qu'il y a une API mais je ne suis pas bien sure de ce qu'il faut faire.
En vous remerciant,
Cordialement,
Pauline

**Comment by equinton** [comment]
Oui, c'est possible d'utiliser l'API pour générer des échantillons, voire les mettre à jour. Il devrait être envisageable soit d'interroger la cyber-carothèque, soit directement l'IGSN, et de verser ensuite les informations dans Collec-Science.
Je rencontre Pascal Calvat cette semaine, je pense qu'on abordera le sujet.
Cordialement,
Éric

**Comment by equinton** [comment]
L'équipe de Pascal travaille sur ce sujet et fait des tests d'alimentation des instances de Collec-Science, je ferme le ticket de mon côté.
