### ISSUE TITLE
BEUG : fonctionnalité prêt

### ISSUE THREAD

**Issue by ghislainGASSIER** [collec-science/collec-science#730]
Bonjour Eric,

Nous sommes en train de tester la fonctionnalité de prêt. Lorsque nous créons un "emprunteur", tout se déroule bien. Cependant, lorsque nous essayons de faire un prêt d'un échantillon, avec "nouveau prêt", nous parvenons au formulaire de "modification d'un prêt". Nous remplissons correctement les informations : emprunteur et  date, puis nous validons. Ensuite, nous sommes redirigés vers la page

Cette page ne fonctionne pasImpossible de traiter cette demande via collec.cerege.fr à l'heure actuelle.
HTTP ERROR 500

le cerege

**Comment by equinton** [comment]
J'ai testé à la fois sur ma machine, sur notre instance en prod et sur l'instance de test (qui dispose de la nouvelle version) : tout fonctionne.
Il faudrait voir dans les logs de la machine si vous avez un message d'erreur.

**Comment by ghislainGASSIER** [comment]
Ok, je vais voir avec julien

**Comment by ghislainGASSIER** [comment]
il n'y a rien dans les dorties de apache

**Comment by equinton** [comment]
Sans message d'erreur, c'est un peu compliqué. À tester, dans le module de requêtes : 
select * from borrowing

Il est possible que ce soit un problème de droits. Dans ce cas là : 
alter table borrowing owner to xxx, xxx étant le compte utilisé pour se connecter depuis l'application.

**Comment by ghislainGASSIER** [comment]
il n'y a aucun résultat pour select * from borrowing

et pour alter table borrowing owner to "mon identifiant"

voici le message d'erreur : La requête ne peut pas contenir d'ordres de modification de la base de données ni porter sur des tables contenant des informations confidentielles._

Comment peut-on faire? Si on fait la remise à jour à la version 24.1.0 ca peut fonctionner?

cordialement et merci à toi pour ton aide,

la team du cerege

**Comment by equinton** [comment]
C'est parce que le compte utilisé par l'application pour se connecter à la base de données ne dispose pas des droits adéquats sur la table borrowing.
La commande de modification (alter table owner to compte_utilise_pour_la_connexion_a_la_base_de_donnees - et pas ton compte de connexion, qui n'a rien à voir) doit être exécutée directement dans la base de données. À voir avec l'administrateur de la machine.

**Comment by equinton** [comment]
[Wed Feb 14 11:38:12.859553 2024] [php:error] [pid 1256] [client 193.49.239.251:2269] PHP Fatal error: Uncaught TypeError: ObjectClass::setLastMovement(): Argument #2 ($movement_id) must be of type int, null given, called in /var/www/html/collec-science/collec-science-git/modules/classes/movement.class.php on line 271 and defined in /var/www/html/collec-science/collec-science-git/modules/classes/object.class.php:1037\nStack trace:\n#0 /var/www/html/collec-science/collec-science-git/modules/classes/movement.class.php(271): ObjectClass->setLastMovement()\n#1 /var/www/html/collec-science/collec-science-git/modules/gestion/borrowing.php(49): Movement->addMovement()\n#2 /var/www/html/collec-science/collec-science-git/framework/controller.php(627): include('...')\n#3 /var/www/html/collec-science/collec-science-git/index.php(3): include('...')\n#4 {main}\n thrown in /var/www/html/collec-science/collec-science-git/modules/classes/object.class.php on line 1037, referer: https://collec.osupytheas.fr/index.php?module=containerborrowingChange&uid=50&borrowing_id=0
