### ISSUE TITLE
BEUG : suppression

### ISSUE THREAD

**Issue by ghislainGASSIER** [collec-science/collec-science#732]
Bonjour Eric,

Il semble qu'il soit impossible de supprimer les échantillons en masse. Lorsque l'on sélectionne la totalité ou une plage d'échantillons CS nous donne :
"_La suppression des échantillons a échoué
Vous ne disposez pas des droits nécessaires pour supprimer l'échantillon 7385_"
Ce message d'erreur intervient alors que nous sommes loggés au niveau admin.

Néanmoins,  lorsque je sélectionne cet échantillon, je clique sur modifier et je peux le supprimer. Ceci n'est qu'un exemple, en effet cela se produit sur différents lots d'échantillons à supprimer

cordialement et merci à toi pour ton aide,
la team du cerege

**Comment by equinton** [comment]
Il faut vérifier si le compte dispose également des droits "collection" : le droit "admin" est un peu particulier, et est indépendant des droits de l'appli.
Pour cela, Administration > ACL login, cliquer sur le login concerné, et vérifier qu'il dispose bien du droit "collection", par exemple : 
![image](https://github.com/collec-science/collec-science/assets/6715861/e918c9fb-be3a-4aac-b56e-0507951e6718)

**Comment by equinton** [comment]
Wed Feb 14 11:58:43.658893 2024] [php:error] [pid 2307] [client 172.20.226.27:59816] PHP Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/collec-science/collec-science-git/modules/classes/sample.class.php:725\nStack trace:\n#0 /var/www/html/collec-science/collec-science-git/modules/classes/sample.class.php(777): Sample->_generateSearch()\n#1 /var/www/html/collec-science/collec-science-git/modules/gestion/sample.php(79): Sample->sampleSearch()\n#2 /var/www/html/collec-science/collec-science-git/framework/controller.php(627): include('...')\n#3 /var/www/html/collec-science/collec-science-git/index.php(3): include('...')\n#4 {main}\n thrown in /var/www/html/collec-science/collec-science-git/modules/classes/sample.class.php on line 725, referer: https://collec.osupytheas.fr/
