### ISSUE TITLE
impossible d'ouvrir un échantillon

### ISSUE THREAD

**Issue by Carol-Moreau** [collec-science/collec-science#735]
Bonjour,

l'échantillon **uid147** (instance paleolab) est impossible à ouvrir.
J'ai essayé à mainte reprises entre 16h17 et 17h09, mais le même message d'erreur apparait:
![image](https://github.com/collec-science/collec-science/assets/147818074/2f14bccb-0835-423f-8a5d-724f4b52c4e2)
Les autres échantillons de la collection (paleoENV) s'ouvrent normalement.

Merci d'avance

Carol

**Comment by equinton** [comment]
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: int - string in /var/www/collec-science/collec-science/display/templates_c/5b969db4ee299afe16aebb25105bb1e5f1fee6d2_0.file.subsampleList.tpl.php:107
