### ISSUE TITLE
CEREGE : popup erreur en mode consult

### ISSUE THREAD

**Issue by ghislainGASSIER** [collec-science/collec-science#743]
Bonjour Eric,

uniquement en mode consultation, un popup d'erreur survient (voir piéce jointe) . Sais-tu d'où cela peut venir ?

Merci de ton soutien.
Cordialement,
L'équipe CEREGE

![screenshot](https://github.com/collec-science/collec-science/assets/58121506/9d8bfdb6-3e54-44e9-bcfb-198384092708)

**Comment by equinton** [comment]
Mise en place d'un correctif temporaire, pas trouvé l'origine
