### ISSUE TITLE
Ajout d'une colonne pour une métadonnée spécifique

### ISSUE THREAD

**Issue by m-lelievre** [collec-science/collec-science#746]
Bonjour, j'ai une question à propos du tableau listant les différents éléments dans un échantillon. 
Dans ce tableau il y a l'option d'afficher une nouvelle colonne contenant l'ensemble des métadonnées pour chaque élément. Serait-il possible de créer une colonne n'affichant qu'une métadonnée spécifiquement? 
Nous voudrions avoir une colonne correspondant à la métadonnée "Amount" seule.

<img width="938" alt="Capture" src="https://github.com/collec-science/collec-science/assets/167065864/e75c19cf-6ecd-4217-a57e-91d8ccc912e3">

**Comment by equinton** [comment]
Bonjour,
Cela me semble particulièrement difficile à mettre en œuvre, rajouter une colonne dans ce tableau très complexe à construire n'est pas évident (la requête permettant de récupérer les données fait plus de 70 lignes, sans compter les critères de recherche, et rajouter une colonne "volante" n'est pas évident).
Sans toucher à la requête, on peut probablement envisager de mettre un filtre sur la colonne "métadonnées" pour n'afficher qu'une information, j'y réfléchirai pour une prochaine version.

**Comment by m-lelievre** [comment]
Merci pour votre réponse, s'il est possible d'en créer un, un filtre serait parfaitement adapté à nos besoins. Très bonne journée à vous.
