### ISSUE TITLE
Intégrer coordonnées GPS aux collections puis l'appliquer aux échantillons

### ISSUE THREAD

**Issue by m-lelievre** [collec-science/collec-science#751]
Bonjour,

Serait-il possible de pouvoir intégrer des coordonnées de longitude et latitude à chaque collection, plutôt qu'à chaque échantillon? Cela serait utile dans le cas où tous les échantillons d'une même collection proviennent du même endroit. Par exemple, en entrant un nouvel échantillon, on pourrait choisir soit "appliquer coordonnées de la collection", soit "nouvelles coordonnées" s'il y a une exception.

Merci,
Bien cordialement,

Marie Lelièvre

**Comment by equinton** [comment]
Bonjour,
Il faudrait qu'on en discute de vive voix. Les coordonnées peuvent être fournies par le lieu de prélèvement, et un lieu de prélèvement peut être "attaché" à une collection.
Au besoin, contactez-moi directement à partir du 13/5, je suis actuellement en congés.
Cordialement,
Éric Quinton.
