### ISSUE TITLE
Modifier/ajouter des Statuts des objets

### ISSUE THREAD

**Issue by m-lelievre** [collec-science/collec-science#752]
Bonjour,

Nous voudrions savoir s'il pourrait être possible de modifier ou créer de nouveaux statuts d'objets, comme il est actuellement possible de le faire pour les types d'échantillons.
Par exemple, dans notre cas il serait utile d'utiliser le statut pour dire de l'échantillon s'il a été tamisé, tamisé et trié, entièrement trié... etc. Actuellement nous avons créé ces catégories dans "types d'échantillons" mais il nous semblerait plus approprié et pratique de les utiliser comme statuts. 

En vous remerciant et vous souhaitant une agréable journée,
Cordialement, 

Marie Lelièvre (Inrae Paleolab)

**Comment by equinton** [comment]
Les statuts ne peuvent pas être modifiés : ils sont manipulés directement par l'application, notamment en cas de prêt.
Par contre, ce que vous voulez indiquer, c'est : 
- soit un état de l'échantillon, qui peut être déclaré dans les métadonnées 
- soit un événement qui arrive à l'échantillon (d'abord brut, puis tamisé, puis lavé, etc.)
selon votre manière de travailler.
Cordialement,
Éric Q.
