### ISSUE TITLE
Ouvrir les pdf des étiquettes dans un nouvel onglet

### ISSUE THREAD

**Issue by m-lelievre** [collec-science/collec-science#753]
Bonjour,

Actuellement , lorsque nous cliquons sur le bouton servant à générer des étiquettes (pour les échantillons comme pour les contenants), l'aperçu des étiquettes s'ouvre sur le même onglet que Collec-Science. Cela n'est pas très pratique, surtout lorsque nous devons faire plusieurs essais avant de trouver le format d'étiquette adapté. 
Serait-il possible de faire s'ouvrir le pdf des étiquettes dans un onglet différent de celui de Collec-Science?

En vous remerciant et vous souhaitant une bonne journée,
Cordialement,

Marie Lelièvre (Inrae Paleolab)

**Comment by equinton** [comment]
C'était le comportement d'il y a quelques années, mais j'ai été confronté à des restrictions liées aux navigateurs (rejet des ouvertures d'onglets supplémentaires dans le contexte de l'impression des étiquettes).
Je referai un test pour voir s'il est possible de revenir à la situation d'origine, que plusieurs collègues m'ont demandé.
