### ISSUE TITLE
Problème pour générer des étiquettes

### ISSUE THREAD

**Issue by Carol-Moreau** [collec-science/collec-science#754]
Bonjour,

je ne parviens pas à générer les étiquettes pour mes nouveaux échantillons (uid:308)

"Erreur lors de la génération du fichier xml
Fichier PDF non généré"

Cela ne fonctionne pas non plus pour les anciens échantillons pour lesquels je viens d'effectuer des modifications (uid:44)
Par contre, ça marche encore pour les anciens échantillons que je n'ai pas touché (uid:46).
J'utilise le modèle d'étiquettes "barcode_uid_short", mais il semble que ça ne fonctionne pas non plus avec les autres modèles.

Pouvez- vous m'aider à résoudre ce problème SVP?
Merci d'avance
Carol

**Comment by Carol-Moreau** [comment]
oups, désolée. C’est paléolab

De : Eric Quinton ***@***.***>
Envoyé : jeudi 23 mai 2024 11:46
À : collec-science/collec-science ***@***.***>
Cc : CAROL MOREAU ***@***.***>; Author ***@***.***>
Objet : Re: [collec-science/collec-science] Problème pour générer des étiquettes (Issue #754)

Sur quelle instance (ma mémoire est limitée...) ?

**Comment by equinton** [comment]
Message lors de la génération du xml : [cs_Paleolab:warn] [pid 3726068] err: Invalid Character Error

Qu'as-tu modifié dans l'échantillon (dans les libellés, notamment) ?

**Comment by Carol-Moreau** [comment]
Pour l’uid 44 par exemple,  je n’ai pas changé le nom, j’ai modifié le type d’échantillon et je l’ai déplacé…

De : Eric Quinton ***@***.***>
Envoyé : jeudi 23 mai 2024 12:10
À : collec-science/collec-science ***@***.***>
Cc : CAROL MOREAU ***@***.***>; Author ***@***.***>
Objet : Re: [collec-science/collec-science] Problème pour générer des étiquettes (Issue #754)


Message lors de la génération du xml : [cs_Paleolab:warn] [pid 3726068] err: Invalid Character Error

Qu'as-tu modifié dans l'échantillon (dans les libellés, notamment) ?

**Comment by equinton** [comment]
Réglé, problème de métadonnées mal codées
