### ISSUE TITLE
Probleme d'affectation de la collection avec API apiv1sampleWrite

### ISSUE THREAD

**Issue by nherrard** [collec-science/collec-science#755]
Bonjour Eric,

J'ai l'impression que l'API apiv1sampleWrite ne prend pas toujours en compte le nom de la collection que je lui donne. 
Je ne suis pas sure de moi car cela fonctionne pour certains échantillons ?!
Exemple pour l'échantillon 27065 de la collection Scorff, après insertion il se retrouve dans la collection Oir, pourtant je suis sure de fournir le bon nom de la collection.
Si on regarde les mouvements sur cet échantillon, dans les commentaires on voit "Echantillon jeté" à chaque fois que j'ai lancé l'API et je ne comprend pas à quoi cela correspond.
As tu une idée du problème ?
Merci
Nadine

**Comment by equinton** [comment]
Rendre la recherche des échantillons dépendante de la collection
