### ISSUE TITLE
erreur popup en mode cosult

### ISSUE THREAD

**Issue by ghislainGASSIER** [collec-science/collec-science#758]
Bonjour Eric,

Nous venons de réaliser la mise à niveau de collec ( Version v24.1.4 du 18/04/2024. ). Cependant, nous rencontrons toujours l'erreur popup en mode cosult (voir pièce jointe). De plus, toujours en mode consult,  il n'est pas possible de sélectionner les colonnes à affichées. Lors de la mise à jour, Julien se demandait s'il était nécessaire de mettre également à jour la base de données, ou s'il n'y avait rien à faire de ce côté-là.

Merci pour ton aide.

Cordialement,

Ghislain
![impression_ecran](https://github.com/collec-science/collec-science/assets/58121506/eea66f4f-cc65-4f25-bb90-2205c82aa81d)

**Comment by ghislainGASSIER** [comment]
Bonjour Eric,

Cette erreur persiste en mode consult, ce qui est assez problématique car de plus en plus de personnes l'utilisent au CEREGE. Nous sommes en version : v24.1.4 du 18/04/2024.

Aurions-nous manqué une mise à jour ?

Cordialement,
L'équipe CEREGE

**Comment by equinton** [comment]
https://github.com/collec-science/collec-science/releases/tag/v24.1.6

La version v24.1.6 a été livrée le 1er juillet, c'est la version v24.1.5 qui corrigeait le problème de popup, comme c'est indiqué dans ce ticket
