### ISSUE TITLE
Bug : Dédoublement d'un échantillon

### ISSUE THREAD

**Issue by m-lelievre** [collec-science/collec-science#762]
Bonjour,

Dans la liste des échantillons, celui qui porte l'UID 108 apparaît deux fois. J'ai modifié le nom d'un des deux pour voir, et la modification est également apparue sur le deuxième (voir capture d'écran ci-jointe). Y a-t-il quelque chose que je puisse faire pour régler ce problème ?

Merci et bonne journée,

Marie Lelièvre
<img width="871" alt="Bug" src="https://github.com/collec-science/collec-science/assets/167065864/3bb4268d-f323-4d9c-a6dd-8ad74c93d91f">

**Comment by equinton** [comment]
C'est lié au fait que l'échantillon est un échantillon dérivé. 
Lors de la recherche initiale, il a été affiché. Au moment où il y a eu un clic sur le signe + de l'échantillon parent,  une requête d'interrogation est partie vers le serveur qui a renvoyé tous les échantillons enfants du parent, indépendamment du fait qu'ils soient - ou non - déjà affichés.
Le programme ne sait pas supprimer l'échantillon qui existait déjà dans la liste, et c'est d'ailleurs particulièrement complexe à coder.
En gros, dès lors qu'on clique sur le + pour avoir la liste des échantillons dérivés, on risque d'avoir les échantillons en doublon dans la liste s'ils étaient déjà affichés.

**Comment by equinton** [comment]
Non, aucun souci, c'est juste de l'affichage ! Les UID sont forcément uniques dans la base de données, c'est un moyen de vérifier les cas un peu spéciaux...
