### ISSUE TITLE
Import en masse avec numéros en colonnes et lettres en lignes

### ISSUE THREAD

**Issue by m-lelievre** [collec-science/collec-science#763]
Re-bonjour,

Lorsque j'essaie d'importer en masse des échantillons, j'obtiens ce message d'erreur : "le champ sample_line n'est pas numérique". En effet, comme certaines de nos boîtes ont des lettres en ligne (cela a été enregistré dans les informations des dites boîtes), j'ai indiqué pour les échantillons devant y être rangés une lettre en sample_line. 

Faut-il continuer à utiliser des chiffres pour les lignes et les colonnes lorsqu'on importe en masse?

(L'autre message d'erreur concerne la date mais cela a été corrigé)

<img width="942" alt="Pb_sample_line_importmasse" src="https://github.com/collec-science/collec-science/assets/167065864/296eeb57-6e04-4be4-aa84-ae96e790acaf">

**Comment by equinton** [comment]
oui, il faut continuer à utiliser les chiffres. Les lettres ne sont générées qu'au moment de l'affichage.
À réfléchir pour savoir si c'est pertinent ou non de faire évoluer le logiciel sur ce point, sachant que, de toute façon, ce sera stocké sous forme numérique en base de données.

**Comment by m-lelievre** [comment]
Très bien, c'est noté pour la prochaine fois. Merci ! 
Bonne journée,

Marie
