### ISSUE TITLE
Pb mise à jour échantillon avec API apiv1sampleWrite

### ISSUE THREAD

**Issue by nherrard** [collec-science/collec-science#765]
Bonjour Eric,

J'ai un problème avec l'API apiv1sampleWrite quand j'essaie de modifier un échantillon dont le numero est dans la même collection mais dans deux type différents.
Exemple sur la collection du Scorff, j'ai un numéro d'écaille 548 et un numero de nageoire 548.
J'ai un message d'erreur "Server error: (500) Internal Server Error" pourtant je lui donne l'uid et le type mais rien à faire. J'ai essayé de ne pas mettre l'identifier mais c'est une donnée obligatoire.

Voici le code pour l'échantillon 548
post_body <- list(
  login = login, 
  token = token,
  module="apiv1sampleWrite",
  identifier="548",
  uid = "89075",
  sample_type_name="Ecaille",
  collection_name="Scorff",
  md_taxon="SAT",
  md_longueur="190",
  md_riviere="Scorff",
  md_secteur = "MDP_PD",
  md_phenotype = "JDIS",
  container_uid = "198805"
)
r <-POST(endpoint,body=post_body)
http_status(r)

Nadine

**Comment by equinton** [comment]
La collection n'autorise pas les identifiants en double. L'api ne retourne pas de message d'erreur, qu'on retrouve dans les logs
Dans la liste des collections, l'indication de l'unicité des identifiants n'est pas correct
