### ISSUE TITLE
Chercher des échantillons pour lesquelles une certaine métadonnée a été remplie en "champ libre"

### ISSUE THREAD

**Issue by m-lelievre** [collec-science/collec-science#768]
Bonjour,

Je voudrais savoir s'il est possible de faire une recherche pour trouver tous les échantillons pour lesquels une métadonnée "champ libre" a été remplie, peu importe ce qui a été rempli. 
En l'occurrence, je voudrais retrouver tous les échantillons pour lesquels j'ai indiqué un poids/volume/quantité dans ma métadonnée "amount". Bien entendu chaque échantillon a une information différente indiquée pour cette métadonnée.

Merci et très bel été,

Marie Lelièvre

**Comment by equinton** [comment]
Bonjour,
Il est possible de réaliser la recherche par le moteur SQL (Objets>Requêtes SQL), avec quelque chose comme :
`select uid, metadata->>'amount' as amount from sample where length(metadata->>'amount') > 0`
