### ISSUE TITLE
suivi des quantité d'échantillon.

### ISSUE THREAD

**Issue by Carol-Moreau** [collec-science/collec-science#770]
Bonjour,
Je travaille sur l'instance paléolab.
J'ai un soucis avec la gestion de quantité d'échantillon quand ceux ci ont des échantillons dérivés.
Je fais des librairies à partir d'ADN. Les librairies sont des "échantillons dérivé" de mes ADN.
Les 2 types d'échantillons se mesurent en volume (µl).
Lorsque je rentre les échantillons dans collec-science, dans la case "Qté de sous-échantillons (µl) :" j'indique le volume de l'échantillon que je suis entrain de créer. Et je fais de même pour les échantillons dérivés. Il s'agit donc du volume de ma librairie, mais ce n'est pas le volume d'échantillon parent (ADN) utilisé pour synthétiser la librairie. Cependant ce volume de librairies est retiré automatiquement du volume d'ADN parent, ce qui fausse toutes mes valeurs.
Pour exemple, voir uid 295, 439  
![image](https://github.com/user-attachments/assets/751c0552-60e2-42ed-be21-c7dca375b90f)
J'ai aussi noté que si on modifie le volume de l'échantillon dérivé après sa création, ce n'est pas pris en compte dans le stock du parent.
(voir uid 439 et 440). ça me permettrait peut-être de contourner le problème.

merci

Carol

**Comment by equinton** [comment]
Tu peux corriger au niveau de l'échantillon parent le volume prélevé, dans l'onglet sous-echantillonnage.
Ton cas est particulier, le volume créé dans les sous-echantillons sont plus importants que les volumes prélevés, je présume parce que tu rajoutes un diluant ou un autre produit.
Je regarderai ce qu'on peut envisager dans la prochaine version pour traiter ça.
