### ISSUE TITLE
import en doublon alors que l'échantillon "n'existe pas" !!

### ISSUE THREAD

**Issue by yannickkk** [collec-science/collec-science#771]
Bonjour Eric,

Je fais un import de masse et l'outil me renvoi:
Une erreur s'est produite pendant l'importation.
Line 831 : error when import sample - SQLSTATE[23505]: Unique violation: 7 ERREUR: la valeur d'une clé dupliquée rompt la contrainte unique « object_identifier_uniq_idx » DETAIL: La clé « (identifier)=(G-20140117-108-serum) » existe déjà.

J'ai essayé de trouver l'échantillon en question, tout d'abord par les menus de filtre de collec, puis par les api et enfin par une requête sql
select uid, identifier, collection_name, sample_type_id, object_status_id
from object
join sample using (uid)
join collection using (collection_id)
join sample_type using (sample_type_id)
where identifier = 'G-20140117-108-serum'

Mais l'échantillon en question reste introuvable. vois tu pourquoi ça fait cela ? merci

**Comment by equinton** [comment]
L'index porte sur la table object, il est possible que ce soit un contenant qui porte cet identifiant

Eric Quinton

Envoyé depuis Proton Mail pour Android

-------- Message d'origine --------

**Comment by yannickkk** [comment]
Non ce n’est pas un contenant !

 

De : Eric Quinton ***@***.***> 
Envoyé : mercredi 28 août 2024 11:14
À : collec-science/collec-science ***@***.***>
Cc : yannickkk ***@***.***>; Author ***@***.***>
Objet : Re: [collec-science/collec-science] import en doublon alors que l'échantillon "n'existe pas" !! (Issue #771)

 

L'index porte sur la table object, il est possible que ce soit un contenant qui porte cet identifiant

Eric Quinton

Envoyé depuis Proton Mail pour Android

-------- Message d'origine --------

**Comment by equinton** [comment]
Je reprends le travail : je viens de voir que l'échantillon a été créé dans la base de données le 28/08/2024 à 16:07:53. Saisie manuelle ou importation via l'api ?

**Comment by yannickkk** [comment]
Bonjour Eric,

 

Bon retour. Tout s’éclaire, je viens de comprendre. Le doublon était dans le fichier que l’on m’a passé pour intégration, pas dans la base de données de Collec.

Ça explique que je ne trouvais pas l’échantillon en question dans collec car détectant un doublon lors de la transaction,  il annulait celle-ci.

J’avais fini par faire l’intégration en nommant l’échantillon  ……-1 et maintenant effectivement les deux échantillons apparaissent bien dans collec à la même heure. 

Bon par contre il faut que je vois avec mon collègue ou est l’échantillon car il l’a positionné à deux endroits différents dans la boite.

Sais tu quand on pourra intégrer des échantillons directement dans une boite via l’API comme on le fait via l’import de masse ?

 

Désolé pour le dérangement ça n’avait rien avoir avec Collec !

Yannick

 

 



 

De : Eric Quinton ***@***.***> 
Envoyé : mercredi 28 août 2024 11:14
À : collec-science/collec-science ***@***.***>
Cc : yannickkk ***@***.***>; Author ***@***.***>
Objet : Re: [collec-science/collec-science] import en doublon alors que l'échantillon "n'existe pas" !! (Issue #771)

 

L'index porte sur la table object, il est possible que ce soit un contenant qui porte cet identifiant

Eric Quinton

Envoyé depuis Proton Mail pour Android

-------- Message d'origine --------
