### ISSUE TITLE
difficulté pour suppression d'échantillons

### ISSUE THREAD

**Issue by Carol-Moreau** [collec-science/collec-science#774]
Bonjour,
Je travaille sur l'instance PaleoLab et j'ai essayé de faire un peu de "ménage" en supprimant les échantillons de notre collection "test".
Lorsque je sélectionne tous les échantillons de la collection et que j'essaie de les supprimer tous d'un coup.
![image](https://github.com/user-attachments/assets/6d47886d-d075-433e-a430-ae534adc436e)
J'ai un message d'erreur qui indique que la suppression a échoué car je "ne dispose pas des droits" pour un des échantillons (ici uid 150)
![image](https://github.com/user-attachments/assets/8a8d369b-9cb1-456f-848f-9f9125b7c2c9)
Quand j'essaie de supprimer uniquement cet échantillon (uid 150), ça indique que la suppression est effectuée, mais en fait, elle ne l'est pas
![image](https://github.com/user-attachments/assets/fefe9b0e-2240-462e-9fe0-bb79b3e560b6)
Il semble que le problème viens du fait que ces échantillons ont des échantillons dérivés.
J'ai essayé de supprimer simultanément un seul échantillon avec tous ses dérivés (en les sélectionnant tous après avoir cliqué sur les "+"). J'ai rencontré le même problème.
Le seul moyen que j'ai trouvé pour les supprimer à été de les supprimer individuellement en remontant du dernier échantillon dérivé a l'échantillon d'origine, ce qui est assez fastidieux.
Serait-il possible de simplifier ce process?

merci d'avance

Carol

**Comment by equinton** [comment]
Ajout d'une fonction de suppression de masse avec les enfants.
