### ISSUE TITLE
Les API sur serveur de test ne fonctionne pas

### ISSUE THREAD

**Issue by nherrard** [collec-science/collec-science#782]
Eric,
Impossible de récupérer un échantillon à partir de l'API sur le serveur de test

voici le programme utilisé
select_collec_science <- function(endpoint = "https://testapi.collec-science.inrae.fr/", 
                                  token_collec_science = "xxxx",
                                  login_collec_science = "colisaapi",
                                  uuid=NA ,
                                  uid=NA) {
  
  module <-  "apiv1sampleDisplay"
   
  if (isFALSE(is.na(uuid))) {
    url_collec_science<-paste0(endpoint, 
                               module,
                               "&uuid=",uuid,
                               "&token=",token_collec_science,
                               "&login=",login_collec_science)
  } else if (isFALSE(is.na(uid))){
    url_collec_science<-paste0(endpoint,
                               module,
                               "&uid=",uid,
                               "&token=",token_collec_science,
                               "&login=",login_collec_science)
  } else {
    stop("Appel de la fonction select_collec_science sans uuid ou uid de l'échantillon ")
  }
  
  req <- httr::GET(url_collec_science)
  
  if (isFALSE(http_error(req))) {
    json <- httr::content(req, as = "text")
    resultat <- fromJSON(json)
  } else {
    message (str_c("Echantillon non trouvé dans colle-science (uuid/uid) : ", uuid, "/", uid))
    resultat <- NA
  }
  return(resultat)
  
}

#lecture d'un echantillon
uuid <- "30946439-8dd5-4f1e-8c42-730e0ce851a5"
ech_collec_science <- select_collec_science(uuid=uuid)

La même fonction fonctionne sur le serveur de prod
Si j'essaie direct avec l'url https://testapi.collec-science.inrae.fr/apiv1sampleDisplay&uuid=30946439-8dd5-4f1e-8c42-730e0ce851a5&token=6e85ea470ce1c7856581735687441512362a8aa6991eae80f2cc525759b4a0d4&login=colisaapi, j'ai le message "page not found"

Je n'ai aucune réponse pour toutes les API

Nadine

**Comment by equinton** [comment]
En get, l'adresse doit avoir cette forme :
https://testapi.collec-science.inrae.fr/apiv1sampleDisplay?uuid=...
Il faut impérativement un point d'interrogation pour séparer l'adresse des variables. Dans ton script, tu utilises exclusivement &, qui est le séparateur de variables _après_ l'url.
Avec ce lien, j'ai un retour null (c'est une autre histoire) : 
https://testapi.collec-science.inrae.fr/apiv1sampleDisplay?uuid=30946439-8dd5-4f1e-8c42-730e0ce851a5&token=6e85ea470ce1c7856581735687441512362a8aa6991eae80f2cc525759b4a0d4&login=colisaapi

Je te régénère le token, vu qu'il est maintenant dans github...

**Comment by nherrard** [comment]
Oups ! je l’avais supprimé du programme mais laissé dans l’url complete, désolée !

Bonne journée
Nadine

En télétravail le lundi et le vendredi

De : Eric Quinton ***@***.***>
Envoyé : jeudi 10 octobre 2024 13:08
À : collec-science/collec-science ***@***.***>
Cc : Nadine Renault ***@***.***>; Author ***@***.***>
Objet : Re: [collec-science/collec-science] Les API sur serveur de test ne fonctionne pas (Issue #782)


En get, l'adresse doit avoir cette forme :
https://testapi.collec-science.inrae.fr/apiv1sampleDisplay?uuid=...
Il faut impérativement un point d'interrogation pour séparer l'adresse des variables. Dans ton script, tu utilises exclusivement &, qui est le séparateur de variables après l'url.
Avec ce lien, j'ai un retour null (c'est une autre histoire) :
https://testapi.collec-science.inrae.fr/apiv1sampleDisplay?uuid=30946439-8dd5-4f1e-8c42-730e0ce851a5&token=6e85ea470ce1c7856581735687441512362a8aa6991eae80f2cc525759b4a0d4&login=colisaapi

Je te régénère le token, vu qu'il est maintenant dans github...

**Comment by nherrard** [comment]
le "?" en get c'est uniquement sur l'api de test ? car si je le mets sur le serveur de prod, ça ne fonctionne plus !

**Comment by equinton** [comment]
oui, parce que l'appli de test a été réécrite avec CodeIgniter : l'appel aux pages a changé.
Dans la version en prod (version _legacy_), les appels sont sous la forme : 
https://site/index.php?module=apiv1sampleDisplay&uuid=xxx

et avec codeIgniter, on a maintenant : 
https://site/apiv1sampleDisplay?uuid=xxx

Une fois que la version en test sera stabilisée, on basculera les instances en prod au fur et à mesure, pour laisser le temps à ceux qui utilisent les api d'adapter les scripts.

**Comment by nherrard** [comment]
Bonjour Eric,
Je reprends les tests sur le serveur de test, voici les conclusions

-          Je n’arrive pas à sélectionner un échantillon à partir de l’uuid, j’ai toujours NA, par contre cela fonctionne avec un uid.

Pas de message d’erreur

> url_collec_science

[1] "https://testapi.collec-science.inrae.fr/apiv1sampleDisplay?uuid=30946439-8dd5-4f1e-8c42-730e0ce851a5&token=xxxxxxx&login=colisaapi"

req <- httr::GET(url_collec_science)

Response [https://testapi.collec-science.inrae.fr/apiv1sampleDisplay?uuid=30946439-8dd5-4f1e-8c42-730e0ce851a5&token=xxxxxx&login=colisaapi]

  Date: 2024-10-23 08:32

  Status: 200

  Content-Type: text/html; charset=UTF-8

  Size: 4 B

>     json <- httr::content(req, as = "text")

>     resultat <- fromJSON(json)

> resultat

NULL



-          La liste des échantillons fonctionne



-          Pour l’insertion et la modification, je n’ai pas les droits
$category
[1] "Client error"

$reason
[1] "Forbidden"

$message
[1] "Client error: (403) Forbidden"



-          Pour la suppression, je n’ai pas de message d’erreur mais la suppression ne se fait pas, je suppose que c’est aussi une histoire de droits ?!
> url_collec_science
[1] https://testapi.collec-science.inrae.fr/apiv1sampleDelete??id=17238&token=xxxxxxx&login=colisaapi
req <- httr::POST(url_collec_science)
Response [https://testapi.collec-science.inrae.fr/apiv1sampleDelete?uid=17238&token=xxxxxx&login=colisaapi]
  Date: 2024-10-23 08:20
  Status: 200
  Content-Type: application/json; charset=UTF-8
  Size: 94 B

Bonne journée
Nadine

En télétravail le lundi et le vendredi

De : Eric Quinton ***@***.***>
Envoyé : jeudi 10 octobre 2024 13:08
À : collec-science/collec-science ***@***.***>
Cc : Nadine Renault ***@***.***>; Author ***@***.***>
Objet : Re: [collec-science/collec-science] Les API sur serveur de test ne fonctionne pas (Issue #782)


En get, l'adresse doit avoir cette forme :
https://testapi.collec-science.inrae.fr/apiv1sampleDisplay?uuid=...
Il faut impérativement un point d'interrogation pour séparer l'adresse des variables. Dans ton script, tu utilises exclusivement &, qui est le séparateur de variables après l'url.
Avec ce lien, j'ai un retour null (c'est une autre histoire) :
https://testapi.collec-science.inrae.fr/apiv1sampleDisplay?uuid=30946439-8dd5-4f1e-8c42-730e0ce851a5&token=6e85ea470ce1c7856581735687441512362a8aa6991eae80f2cc525759b4a0d4&login=colisaapi

Je te régénère le token, vu qu'il est maintenant dans github...

**Comment by equinton** [comment]
Pour les droits de modification, il faut rajouter le nom de la collection dans les paramètres d'envoi.
Avec l'API, il est possible de changer la collection d'un échantillon, et plusieurs contrôles sont effectués avant d'autoriser l'opération.
Sauf si le compte utilisé n'accède qu'à une seule collection, le nom de la collection "cible" doit être indiqué.

Pour la suppression, je n'ai pas eu de souci, j'ai supprimé un échantillon dans la collection colisa dans l'instance de test. Il faudrait vérifier les paramètres transmis au serveur.

La recherche par uuid fonctionne maintenant.

**Comment by nherrard** [comment]
**En ajout et en modification j'ai bien le nom de la collection dans les paramètres d'envoi mais j'ai toujours le message [1] "Client error: (403) Forbidden"**
en utilisant 
>post_body
{"login":"colisaapi","token":"xxx","module":"apiv1sampleWrite","identifier":"essai_nadine","sample_type_name":"Ecaille","collection_name":"COLISA","sampling_date":"2022-06-30","md_taxon":"TRF","md_longueur":155,"md_riviere":"Roche","md_phenotype":"JSIN","md_secteur":"RR11","referent_name":"Starck","referent_firstname":"Agnès","country_code":"FR","country_origin_code":"FR"} 

POST(endpoint,body=post_body) 

**Pour la suppression, je n'y arrive toujours pas, exemple avec l'uid 17237**
> url_collec_science
[1] "https://testapi.collec-science.inrae.fr/apiv1sampleDelete&token=xxx&login=colisaapi&uid=17237"
> httr::POST(url_collec_science)
Response [https://testapi.collec-science.inrae.fr/apiv1sampleDelete&token=xxx&login=colisaapi&uid=17237]
  Date: 2024-11-12 14:52
  Status: 404
  Content-Type: application/json; charset=UTF-8
  Size: 2 B

**Comment by equinton** [comment]
Pour la mise à jour, tu dois avoir :
- endpoint : https://testapi.collec-science.inrae.fr/apiv1sampleWrite
- post_body : les champs login, token, identifier (etc.). Il faut virer le champ "module" (version legacy de l'appli)

Pour la suppression, voici les paramètres qui fonctionnent :
Méthode : POST
Adresse : https://testapi.collec-science.inrae.fr/apiv1sampleDelete
Paramètres
Array
(
    [login] => colisaapi
    [token] => xxxxx
    [uid] => 17237
)
Résultat : 
Array
(
    [error_code] => 200
    [error_message] => processed
)

Le 17237 n'existe plus dans la base de données...

**Comment by nherrard** [comment]
je progresse ...
en modification je n'ai toujours pas les droits 
> endpoint
[1] "https://testapi.collec-science.inrae.fr/apiv1sampleWrite"
> post_body
{"login":"colisaapi","token":"xxx","identifier":"essai_nadine","sample_type_name":"Ecaille","collection_name":"COLISA","sampling_date":"2022-06-30","md_taxon":"SAT","md_longueur":120,"md_riviere":"Oir","referent_name":"Starck","referent_firstname":"Agnès","country_code":"FR","country_origin_code":"FR"} 
> POST(endpoint,body=post_body)
Response [https://testapi.collec-science.inrae.fr/apiv1sampleWrite]
  Date: 2024-11-12 15:10
  Status: 200
  Content-Type: application/json; charset=UTF-8
  Size: 127 B
> content(r, "text")
[1] "{\"error_code\":520,\"error_message\":\"Unknown error\",\"error_detail\":\"La collection n'a pas été fournie ou n'est pas autorisée\"}"

**Comment by equinton** [comment]
Méthode : POST
Adresse : https://testapi.collec-science.inrae.fr/apiv1sampleWrite
Paramètres
Array
(
    [login] => colisaapi
    [token] => xxxx
    [identifier] => essai_nadine
    [sample_type_name] => Ecaille
    [collection_name] => COLISA
    [sampling_date] => 2022-06-30
    [md_taxon] => SAT
    [md_longueur] => 120
    [md_riviere] => Oir
    [referent_name] => Starck
    [referent_firstname] => Agnès
    [country_code] => FR
    [country_origin_code] => FR
)
Résultat : 
(
    [error_code] => 200
    [error_message] => processed
    [uid] => 17340
)

Vérifie ton token, il n'est pas impossible qu'il soit erroné.

**Comment by nherrard** [comment]
non il est bon car je viens de supprimer un échantillon avec

**Comment by nherrard** [comment]
Bonsoir Erice
J’ai repris les tests à tête reposée, c’est bon tout fonctionne
Merci

Nadine

Le 12 nov. 2024 à 16:29, Eric Quinton ***@***.***> a écrit :

﻿

Méthode : POST
Adresse : https://testapi.collec-science.inrae.fr/apiv1sampleWrite
Paramètres
Array
(
[login] => colisaapi
[token] => xxxx
[identifier] => essai_nadine
[sample_type_name] => Ecaille
[collection_name] => COLISA
[sampling_date] => 2022-06-30
[md_taxon] => SAT
[md_longueur] => 120
[md_riviere] => Oir
[referent_name] => Starck
[referent_firstname] => Agnès
[country_code] => FR
[country_origin_code] => FR
)
Résultat :
(
[error_code] => 200
[error_message] => processed
[uid] => 17340
)

Vérifie ton token, il n'est pas impossible qu'il soit erroné.
