### ISSUE TITLE
Tous les types d'échantillons cochés par défaut lors de la création d'une collection

### ISSUE THREAD

**Issue by fanglard** [collec-science/collec-science#787]
Bonjour,
Lors de la  création d’une collection, pour rattacher le/les types d’échantillons, serait-il possible qu’ils soient tous cochés par défaut (puis décocher) ou d’avoir un bouton pour le faire ?
Merci
Frédéric

**Comment by equinton** [comment]
cf. #785 
Dispo dans la version de test.
